Use collections.abc.Mapping
Untested change to improve Python 3.10 support.

Latest release gives the following errors when run with Python 3.10:

```
2021-10-07 15:35:58,530 ERROR    errbot.backends.base      Exception occurred in serve_once:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/errbot/backends/base.py", line 861, in serve_forever
    if self.serve_once():
  File "/usr/local/lib/python3.10/site-packages/errbot/backends/slack.py", line 421, in serve_once
    self.auth = self.api_call("auth.test", raise_errors=False)
  File "/usr/local/lib/python3.10/site-packages/errbot/backends/slack.py", line 378, in api_call
    if not isinstance(response, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```