Revert "Fix "AttributeError: JID instance has no attribute '__len__'""
This reverts commit 082d95fdb4878936332abe5102ce046cbb602214, which
caused a regression with template rendering:

TypeError: render() argument after ** must be a mapping, not str